apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-new
  template:
    metadata:
      labels:
        app: kubernetes-new
    spec:
      containers:
      - name: kubernetes-new
        image: kubernetes-new:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-new
spec:
  selector:
    app: kubernetes-new
  ports:
  - port: 5000
    targetPort: 5000
